Repository TeonaRusu/PSBDP, pull requests merged in 2019-01, with the labels that each got.

#7 add reservation table
  _install/scripts_insert_data/RESERVATION.sql
  _install/scripts_procedures/GET_RESERVATIONS_PROCEDURE.sql
  application/Controller/ReservationController.php
  application/Model/Reservation.php
  application/view/reservation/list.php
Labels: enhancement

#8 update reservation procedure
  _install/scripts_procedures/GET_RESERVATION_DETAILS.sql
  _install/scripts_procedures/UPDATE_RESERVATION_PROCEDURE.sql
  application/Controller/ReservationController.php
  application/Model/Reservation.php
  application/view/reservation/edit.php
  application/view/reservation/list.php
Labels: enhancement, help wanted

#11 css for forms
  application/Controller/RoomController.php
  application/view/reservation/edit.php
  application/view/room/add.php
  application/view/room/form.php
Labels: structure
